package token_test

import (
	"crypto/rand"
	"crypto/rsa"
	"encoding/base64"
	"math/big"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/enunezf/sentinel/internal/domain"
	"github.com/enunezf/sentinel/internal/token"
)

// newTestManager creates a Manager with freshly generated RSA 2048 keys, no PEM files needed.
func newTestManager(t *testing.T) *token.Manager {
	t.Helper()
	privKey, err := rsa.GenerateKey(rand.Reader, 2048)
	require.NoError(t, err, "generate RSA key pair")
	return token.NewManagerFromKey(privKey)
}

func testUser() *domain.User {
	return &domain.User{
		ID:       uuid.MustParse("550e8400-e29b-41d4-a716-446655440000"),
		Username: "jperez",
		Email:    "jperez@sodexo.com",
	}
}

// TestGenerateAccessToken_Structure verifies header, payload claims, and that the
// resulting token is a well-formed three-part JWT (header.payload.signature).
func TestGenerateAccessToken_Structure(t *testing.T) {
	mgr := newTestManager(t)
	user := testUser()
	roles := []string{"chef", "bodeguero-temporal"}
	ttl := 60 * time.Minute

	tokenStr, err := mgr.GenerateAccessToken(user, "hospitality-app", roles, ttl)
	require.NoError(t, err)
	require.NotEmpty(t, tokenStr)

	// Must be three dot-separated segments.
	parts := splitToken(tokenStr)
	assert.Len(t, parts, 3, "JWT must have header.payload.signature")

	// Header must encode alg=RS256 and typ=JWT.
	headerJSON, err := base64.RawURLEncoding.DecodeString(parts[0])
	require.NoError(t, err)
	assert.Contains(t, string(headerJSON), `"RS256"`)
	assert.Contains(t, string(headerJSON), `"JWT"`)
	// kid must be present.
	assert.Contains(t, string(headerJSON), `"kid"`)
	assert.Contains(t, string(headerJSON), token.KID)
}

// TestValidateToken_Success ensures that a token generated by the manager is
// verifiable using the same manager (public key).
func TestValidateToken_Success(t *testing.T) {
	mgr := newTestManager(t)
	user := testUser()

	tokenStr, err := mgr.GenerateAccessToken(user, "hospitality-app", []string{"chef"}, 60*time.Minute)
	require.NoError(t, err)

	claims, err := mgr.ValidateToken(tokenStr)
	require.NoError(t, err)
	require.NotNil(t, claims)

	assert.Equal(t, user.ID.String(), claims.Sub)
	assert.Equal(t, user.Username, claims.Username)
	assert.Equal(t, user.Email, claims.Email)
	assert.Equal(t, "hospitality-app", claims.App)
	assert.Equal(t, []string{"chef"}, claims.Roles)
}

// TestValidateToken_Expired validates that a token whose exp is in the past is rejected.
func TestValidateToken_Expired(t *testing.T) {
	mgr := newTestManager(t)
	user := testUser()

	// TTL of -1 second makes exp = iat - 1 (already expired).
	tokenStr, err := mgr.GenerateAccessToken(user, "app", []string{}, -1*time.Second)
	require.NoError(t, err)

	_, err = mgr.ValidateToken(tokenStr)
	assert.Error(t, err, "expired token must be rejected")
}

// TestValidateToken_InvalidSignature verifies that a token signed with a different
// RSA key is rejected by the validator.
func TestValidateToken_InvalidSignature(t *testing.T) {
	signerMgr := newTestManager(t)
	verifierMgr := newTestManager(t) // different key pair

	user := testUser()
	tokenStr, err := signerMgr.GenerateAccessToken(user, "app", []string{}, 60*time.Minute)
	require.NoError(t, err)

	_, err = verifierMgr.ValidateToken(tokenStr)
	assert.Error(t, err, "token signed with wrong key must be rejected")
}

// TestClaims_Complete checks that all required claims are present in the validated output.
func TestClaims_Complete(t *testing.T) {
	mgr := newTestManager(t)
	user := testUser()
	roles := []string{"chef"}

	tokenStr, err := mgr.GenerateAccessToken(user, "hospitality-app", roles, 60*time.Minute)
	require.NoError(t, err)

	claims, err := mgr.ValidateToken(tokenStr)
	require.NoError(t, err)

	assert.NotEmpty(t, claims.Sub, "sub must be present")
	assert.NotEmpty(t, claims.Username, "username must be present")
	assert.NotEmpty(t, claims.Email, "email must be present")
	assert.NotEmpty(t, claims.App, "app must be present")
	assert.NotEmpty(t, claims.Roles, "roles must be present")
	assert.NotZero(t, claims.Iat, "iat must be present")
	assert.NotZero(t, claims.Exp, "exp must be present")
	assert.NotEmpty(t, claims.Jti, "jti must be present")
}

// TestJTI_Unique verifies that two consecutively generated tokens have distinct jti values.
func TestJTI_Unique(t *testing.T) {
	mgr := newTestManager(t)
	user := testUser()

	t1, err := mgr.GenerateAccessToken(user, "app", []string{}, 60*time.Minute)
	require.NoError(t, err)
	t2, err := mgr.GenerateAccessToken(user, "app", []string{}, 60*time.Minute)
	require.NoError(t, err)

	c1, err := mgr.ValidateToken(t1)
	require.NoError(t, err)
	c2, err := mgr.ValidateToken(t2)
	require.NoError(t, err)

	assert.NotEqual(t, c1.Jti, c2.Jti, "consecutive tokens must have unique jti")
}

// TestGenerateJWKS_Format validates that the JWKS document contains all required RFC 7517 fields.
func TestGenerateJWKS_Format(t *testing.T) {
	mgr := newTestManager(t)
	jwks := mgr.GenerateJWKS()

	require.Len(t, jwks.Keys, 1)
	key := jwks.Keys[0]

	assert.Equal(t, "RSA", key.Kty, "kty must be RSA")
	assert.Equal(t, "RS256", key.Alg, "alg must be RS256")
	assert.Equal(t, "sig", key.Use, "use must be sig")
	assert.Equal(t, token.KID, key.Kid, "kid must match configured KID")
	assert.NotEmpty(t, key.N, "n (modulus) must be present")
	assert.NotEmpty(t, key.E, "e (exponent) must be present")

	// e must decode to a valid big-endian integer (typically 65537 / AQAB).
	eBytes, err := base64.RawURLEncoding.DecodeString(key.E)
	require.NoError(t, err)
	e := new(big.Int).SetBytes(eBytes)
	assert.Equal(t, int64(65537), e.Int64(), "e must equal 65537")
}

// TestTTL_AccessToken verifies that exp = iat + 3600 for a 60-minute TTL.
func TestTTL_AccessToken(t *testing.T) {
	mgr := newTestManager(t)
	user := testUser()

	ttl := 60 * time.Minute
	before := time.Now().Unix()
	tokenStr, err := mgr.GenerateAccessToken(user, "app", []string{}, ttl)
	require.NoError(t, err)
	after := time.Now().Unix()

	claims, err := mgr.ValidateToken(tokenStr)
	require.NoError(t, err)

	diff := claims.Exp - claims.Iat
	assert.EqualValues(t, 3600, diff, "exp - iat must equal 3600 seconds")

	// iat must be within the test window.
	assert.GreaterOrEqual(t, claims.Iat, before)
	assert.LessOrEqual(t, claims.Iat, after)
}

// TestKID_InHeader verifies that the kid in the JWT header matches the configured KID constant.
func TestKID_InHeader(t *testing.T) {
	mgr := newTestManager(t)
	user := testUser()

	tokenStr, err := mgr.GenerateAccessToken(user, "app", []string{}, 60*time.Minute)
	require.NoError(t, err)

	parts := splitToken(tokenStr)
	require.Len(t, parts, 3)

	headerJSON, err := base64.RawURLEncoding.DecodeString(parts[0])
	require.NoError(t, err)
	assert.Contains(t, string(headerJSON), token.KID,
		"kid in JWT header must match the configured KID")
}

// splitToken splits a JWT string into its three parts by '.'.
func splitToken(s string) []string {
	var parts []string
	start := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '.' {
			parts = append(parts, s[start:i])
			start = i + 1
		}
	}
	parts = append(parts, s[start:])
	return parts
}
